const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');const engine=require('../src/cloud-autosave.js');
test('UI persist autosaves outside wrappers and restores recovered work automatically',async()=>{
  const nodes=new Map(),local=new Map(),timers=new Map(),writes=[];let id=0;
  const node=key=>{if(!nodes.has(key))nodes.set(key,{style:{},textContent:'',hidden:true,value:'',classList:{add(){},remove(){}},before(){},focus(){}});return nodes.get(key);};
  const base={products:[],inputs:[],history:[],categories:[],laborSettings:{salary:0,hours:1},view:'dashboard'};
  const context={ForgeServicesReady:Promise.resolve(),ForgeCloudAutosave:engine,state:structuredClone(base),DEFAULT_STATE:base,settings:()=>'',render(){},exportBackup(){},toast(){},location:{reload(){}},document:{getElementById:node,createElement:()=>node('bar'),querySelectorAll:()=>[]},localStorage:{getItem:k=>local.get(k)||null,setItem:(k,v)=>local.set(k,v),removeItem:k=>local.delete(k)},setTimeout:(fn,ms)=>{timers.set(++id,{fn,ms});return id;},clearTimeout:id=>timers.delete(id),addEventListener(){},ForgeServices:{auth:{current:()=>({userId:'u'}),signIn:async()=>({userId:'u',email:'qa@example.com'})},repository:{validate:d=>d,load:async()=>structuredClone(base),save:async(s,d)=>writes.push(d)}}};context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync(require.resolve('../src/cloud-ui-v2.js'),'utf8'),context);await new Promise(resolve=>setImmediate(resolve));assert.equal(node('loginError').textContent,'');
  context.state.history.push('changed outside mutation wrapper');assert.equal(context.saveWorkspace(),true);assert.equal(timers.size,1);assert.equal(node('cloudRetry').hidden,true);await node('cloudRetry').onclick();assert.equal(writes.length,1);assert.equal(node('cloudStatus').textContent,'Salvo no Firebase');assert.equal(local.size,0);
  local.set('forgecost_pending_u',JSON.stringify({base,data:{...base,history:['recovered']}}));await node('loginForm').onsubmit({preventDefault(){},currentTarget:{querySelector:()=>({disabled:false})}});assert.equal(timers.size,1);await node('cloudRetry').onclick();assert.deepEqual(writes.at(-1).history,['recovered']);assert.equal(local.size,0);
});
