function saveWorkspace(){try{ForgeServices.repository.save(ForgeServices.auth.current(),state);return true}catch(error){toast('Não foi possível salvar. Exporte um backup antes de sair.');return false}}
const originalDetail=detail;
detail=function(){const p=state.products.find(x=>x.id===state.selectedProduct);return originalDetail()+`<section class="panel labor-panel"><div class="panel-head"><h3>PROCESSOS E MÃO DE OBRA</h3><button class="btn primary small" onclick="processForm(${p.id})">+ Processo</button></div><div class="kpi-list">${p.labor.map((x,i)=>`<div class="kpi-row"><span>${escapeHtml(x.name)} • ${num(x.time)} h / unidade</span><b>${money(x.time*rate())}</b><div class="row-actions"><button class="btn small" onclick="processForm(${p.id},${i})">Editar</button><button class="btn small danger" onclick="deleteProcess(${p.id},${i})">Excluir</button></div></div>`).join('')||'<p class="empty">Adicione os tempos de produção por unidade.</p>'}</div></section>`};
function processForm(pid,index=null){const item=index===null?{name:'',time:1}:state.products.find(p=>p.id===pid).labor[index];modal('Processo de fabricação',`<div class="form-grid">${field('processName','Processo',item.name)}${field('processHours','Horas por unidade',item.time,'number')}</div>`,`<button class="btn" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveProcess(${pid},${index})">Salvar</button>`)}
function saveProcess(pid,index){const name=v('processName').trim(),time=+v('processHours');if(!name||!Number.isFinite(time)||time<=0)return toast('Informe processo e tempo positivo');const p=state.products.find(p=>p.id===pid);if(index===null)p.labor.push({name,time});else p.labor[index]={name,time};hist('Processo atualizado',p.name);closeModal();render()}
function deleteProcess(pid,index){if(confirm('Excluir processo?')){const p=state.products.find(p=>p.id===pid);p.labor.splice(index,1);hist('Processo excluído',p.name);render()}}
const originalSettings=settings;
settings=function(){return originalSettings()+`<section class="panel labor-panel"><div class="panel-head"><h3>BACKUP E MIGRAÇÃO</h3></div><div class="breakdown"><p>Os dados pertencem ao workspace demo deste e-mail, neste navegador. Esta separação local não oferece segurança multiusuário.</p><div class="toolbar"><button class="btn" onclick="exportBackup()">Exportar backup JSON</button><button class="btn" onclick="document.getElementById('backupFile').click()">Importar backup</button><button class="btn" onclick="importLegacy()">Importar dados da V2 neste navegador</button><input type="file" id="backupFile" accept=".json,application/json" hidden onchange="importBackup(this.files[0])"></div><p class="sub">A V2 original permanece intacta. Para transferir entre endereços ou navegadores, exporte o localStorage forgecost_v2 como JSON e importe aqui.</p></div></section>`};
function exportBackup(){const blob=new Blob([JSON.stringify({version:3,data:state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='forgecost-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function importBackup(file){if(!file)return;try{const parsed=JSON.parse(await file.text());const data=ForgeServices.repository.validate(parsed.data||parsed);if(confirm('Substituir os dados deste workspace pelo backup?')){state=structuredClone(data);state.view='dashboard';state.selectedProduct=null;persist();render()}}catch(e){toast('Não foi possível importar: arquivo inválido.')}}
function importLegacy(){try{const data=ForgeServices.repository.legacy();if(!data)return toast('Não há dados V2 neste endereço. Use um backup JSON.');if(confirm('Importar os dados da V2 para este e-mail e substituir o workspace atual?')){state=structuredClone(data);state.view='dashboard';persist();render();toast('V2 importada; original preservada')}}catch(e){toast('Não foi possível ler a base V2.')}}
function setTheme(theme){document.documentElement.dataset.theme=theme;document.querySelectorAll('.theme-toggle').forEach(b=>{b.textContent=theme==='dark'?'☀ Claro':'☾ Escuro';b.setAttribute('aria-label',theme==='dark'?'Usar tema claro':'Usar tema escuro')});try{localStorage.setItem('forgecost_theme',theme)}catch{} }
let preferred='dark';try{preferred=localStorage.getItem('forgecost_theme')||'dark'}catch{}setTheme(preferred==='light'?'light':'dark');
document.querySelectorAll('.theme-toggle').forEach(b=>b.onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
$('loginForm').onsubmit=async e=>{e.preventDefault();const button=e.currentTarget.querySelector('[type=submit]');button.disabled=true;$('loginError').textContent='';try{const session=await ForgeServices.auth.signIn($('email').value,$('password').value);state=await ForgeServices.repository.load(session,DEFAULT_STATE);state.view='dashboard';state.selectedProduct=null;$('password').value='';$('sessionEmail').textContent=session.email;$('loginScreen').hidden=true;$('appShell').hidden=false;render();$('content').setAttribute('tabindex','-1');$('content').focus()}catch(error){await ForgeServices.auth.signOut();$('loginError').textContent='Não foi possível abrir os dados locais. Verifique o armazenamento do navegador; os dados existentes não foram sobrescritos.'}finally{button.disabled=false}};
$('logoutBtn').onclick=async()=>{if(!saveWorkspace())return;await ForgeServices.auth.signOut();state=structuredClone(DEFAULT_STATE);closeModal();$('content').innerHTML='';$('appShell').hidden=true;$('loginScreen').hidden=false;$('email').focus()};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();$('sidebar').classList.remove('open')}});
