let shopeeDraft=null,shopeeOwner=null;
// The cloud mutation adapter captures this notifier before installing its save wrapper.
if(typeof window.toast!=='function')window.toast=function(message){const node=document.getElementById('toast');node.textContent=message;node.classList.add('show');clearTimeout(window.forgeToastTimer);window.forgeToastTimer=setTimeout(()=>node.classList.remove('show'),4000)};
function shopeeField(key,label){return `<label class="field"><span>${label}</span><input id="sh-${key}" type="number" min="0" step="${key==='units'?'1':'0.01'}" value="${shopeeDraft[key]}" oninput="shopeeUpdate()"></label>`}
function shopeeSelect(key,label,options){return `<label class="field"><span>${label}</span><select id="sh-${key}" onchange="shopeeUpdate()">${options.map(([value,text])=>`<option value="${value}" ${shopeeDraft[key]===value?'selected':''}>${text}</option>`).join('')}</select></label>`}
function shopee(){
  const owner=ForgeServices.auth.current()?.userId;
  if(!shopeeDraft||shopeeOwner!==owner){shopeeOwner=owner;shopeeDraft={...ForgeShopee.defaults,...state.shopee?.settings};}
  return head('MARKETPLACE','Shopee','Preço, repasse e margem por anúncio. NF padrão de 12%; confirme as cobranças da sua conta.',`<button class="btn" onclick="shopeePrint()">Imprimir / PDF</button><button class="btn primary" onclick="saveShopeeSettings()">Salvar parâmetros</button>`)+`
  <section class="panel"><div class="panel-head"><h3>PRODUTO E VENDA</h3><span>Cálculo por unidade comercial / kit do anúncio</span></div><div class="shopee-fields">
  <label class="field"><span>Produto da ficha técnica</span><select id="sh-product" onchange="shopeeChoose(this.value)"><option value="">Simulação livre</option>${sortedProducts().map(p=>`<option value="${escapeHtml(p.id)}">${escapeHtml(p.name)}</option>`).join('')}</select></label>
  ${shopeeField('cost','Custo de fabricação por peça R$')}${shopeeField('units','Peças no kit anunciado')}${shopeeField('price','Preço do anúncio R$')}${shopeeField('margin','Margem desejada sobre a venda %')}${shopeeField('nf','Imposto NF sobre a venda %')}
  ${shopeeField('packaging','Embalagem extra por anúncio R$')}${shopeeField('freight','Frete / ajuste pago pelo vendedor R$')}${shopeeField('other','Outros custos por anúncio R$')}${shopeeField('discountRate','Desconto custeado pelo vendedor %')}${shopeeField('discount','Cupom custeado pelo vendedor R$')}
  </div><p class="calc-note">A ficha inclui os materiais, embalagem e mão de obra cadastrados. Use embalagem extra apenas para despesas adicionais. Em kit, o custo é multiplicado pelas peças e a taxa fixa incide uma vez por kit comercial. Subsídio Pix pago pela Shopee não é desconto do vendedor.</p><button class="btn" onclick="saveShopeeProduct()">Salvar simulação deste produto</button></section>
  <section class="panel"><div class="panel-head"><h3>TAXAS DA CONTA</h3><button class="btn small" onclick="shopeeObserved()">Usar estimativa da conta analisada</button></div><div class="shopee-fields">
  ${shopeeSelect('period','Tabela de comissão',[['oct2026','A partir de 01/10/2026'],['sep2026','Março a setembro de 2026']])}
  ${shopeeSelect('seller','Perfil de vendedor',[['standard','CNPJ / CPF sem adicional'],['cpfHigh','CPF acima de 450 pedidos em 90 dias']])}
  ${shopeeField('extraRate','Taxa adicional da conta %')}${shopeeField('affiliate','Afiliados %')}${shopeeField('advance','Acelera / antecipação % do saldo')}${shopeeField('returnFee','Ajuste / devolução por anúncio R$')}
  ${shopeeSelect('adsMode','Shopee Ads',[['none','Sem Ads'],['reserve','Reserva de recarga (desconta do repasse)'],['spend','Gasto efetivo (custo de marketing)']])}${shopeeField('adsRate','Ads % da venda')}
  </div><p class="calc-note">Taxas adicionais, Ads e Acelera começam em zero: não são universais. Para reproduzir a conta analisada, confira o adicional observado de 3,5%, a reserva Ads de 4% e Acelera de 3,5%. Reserva e gasto efetivo são alternativas para evitar cobrança duplicada. Acelera é estimado sobre o saldo após comissão, taxas adicionais, afiliados e reserva, antes dos ajustes fixos; o extrato pode usar outra base.</p></section>
  <div id="shopee-result" aria-live="polite"></div>
  <section class="panel"><div class="panel-head"><h3>TABELA AUTOMÁTICA DE COMISSÃO</h3><a class="inline-link" target="_blank" rel="noopener" href="https://seller.br.shopee.cn/edu/article/26839/Comissao-para-vendedores-CNPJ-e-CPF-em-2026">Fonte: Central do Vendedor Shopee ↗</a></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Valor efetivo do item / kit</th><th>Comissão</th><th>Taxa fixa desde 01/10/2026</th></tr></thead><tbody><tr><td>Abaixo de R$ 9</td><td>20%</td><td>50% do valor do item</td></tr><tr><td>R$ 9 a R$ 79,99</td><td>20%</td><td>R$ 4,50</td></tr><tr><td>R$ 80 a R$ 99,99</td><td>14%</td><td>R$ 16</td></tr><tr><td>R$ 100 a R$ 199,99</td><td>14%</td><td>R$ 20</td></tr><tr><td>R$ 200 ou mais</td><td>14%</td><td>R$ 26</td></tr></tbody></table></div><p class="calc-note">Até setembro: taxa fixa de R$ 4 abaixo de R$ 80; regra de metade do preço abaixo de R$ 8. CPF de alto volume: adicional de R$ 3 a partir de R$ 12; abaixo disso, a regra regressiva precisa ser confirmada e não é simulada. A recomendação procura o menor preço em todas as faixas. Ao cruzar R$ 80, R$ 100 ou R$ 200, a taxa fixa pode aumentar e reduzir a margem.</p></section>`;
}
function shopeeRead(){const d={...shopeeDraft};for(const k of Object.keys(ForgeShopee.defaults)){const el=$('sh-'+k);if(el)d[k]=typeof ForgeShopee.defaults[k]==='number'?Number(el.value):el.value;}return ForgeShopee.validate(d)}
function shopeeUpdate(){
  const el=$('shopee-result');if(!el)return;
  try{
    shopeeDraft=shopeeRead();const r=ForgeShopee.calculate(shopeeDraft),target=ForgeShopee.suggest(shopeeDraft),zero=ForgeShopee.suggest(shopeeDraft,0),ok=r.margin+1e-7>=shopeeDraft.margin;
    const status=r.price<=0?'Informe o preço atual':r.profit<0?'Prejuízo':ok?'Meta de margem atingida':'Margem abaixo da meta';
    const rows=[['Venda após desconto do vendedor',r.price],['Comissão Shopee '+r.tier.rate+'%',-r.commission],['Taxa fixa da faixa (inclui adicional CPF, se houver)',-r.fixed],['Taxa adicional da conta',-r.extra],['Afiliados',-r.affiliate],['Reserva Ads',-r.reserve],['Acelera / antecipação',-r.advance],['Ajuste / devolução',-shopeeDraft.returnFee],['Frete pago pelo vendedor',-shopeeDraft.freight],['Repasse estimado da carteira',r.repasse],['NF '+shopeeDraft.nf+'%',-r.nf],['Fabricação das peças do anúncio',-r.production],['Embalagem adicional',-shopeeDraft.packaging],['Outros custos',-shopeeDraft.other],['Ads: gasto efetivo',-r.marketing],['Lucro após os custos informados',r.profit]];
    el.innerHTML=`<section class="panel"><div class="panel-head"><h3>RESULTADO DA SIMULAÇÃO</h3><strong style="color:var(--${r.profit<0?'danger':ok?'good':'warn'})">${status}</strong></div><div class="shopee-metrics">${[['Repasse estimado',money(r.repasse)],['Lucro estimado',money(r.profit)],['Margem sobre a venda',num(r.margin)+'%'],['Preço do anúncio para '+num(shopeeDraft.margin)+'%',target===null?'Meta inviável':money(target)],['Preço mínimo sem prejuízo',zero===null?'Inviável':money(zero)]].map(([a,b])=>`<div class="summary-item"><small>${a}</small><b>${b}</b></div>`).join('')}</div><p class="calc-note">Margem = lucro ÷ venda efetiva. A sugestão inclui os descontos informados e todas as faixas; arredondamentos podem variar alguns centavos no extrato. Lucro considera somente os custos preenchidos: inclua despesas operacionais em “Outros custos”. Preço calculado é simulação, não altera o anúncio na Shopee.</p><div class="table-wrap"><table class="data-table"><thead><tr><th>Composição por anúncio / kit</th><th>Valor</th></tr></thead><tbody>${rows.map(([a,b])=>`<tr><td>${a}</td><td class="money">${money(b)}</td></tr>`).join('')}</tbody></table></div></section>`;
  }catch(e){el.innerHTML=`<section class="panel"><p role="alert" style="color:var(--danger)">${escapeHtml(e.message)}</p></section>`;}
}
function shopeeChoose(id){const p=state.products.find(p=>String(p.id)===id);shopeeDraft={...ForgeShopee.defaults,...state.shopee?.settings,...(p?state.shopee?.products?.[id]:{}),cost:p?pc(p).total:0};for(const k of Object.keys(ForgeShopee.defaults))if($('sh-'+k))$('sh-'+k).value=shopeeDraft[k];shopeeUpdate()}
function shopeeObserved(){for(const [k,value] of Object.entries({extraRate:3.5,adsMode:'reserve',adsRate:4,advance:3.5,returnFee:.49}))$('sh-'+k).value=value;shopeeUpdate();toast('Estimativa aplicada. Confira as bases e ajustes no extrato atual.')}
function saveShopeeSettings(){try{shopeeDraft=shopeeRead();state.shopee={...state.shopee,settings:Object.fromEntries(Object.entries(shopeeDraft).filter(([k])=>!['cost','price','units','packaging','freight','other','discount','discountRate','returnFee'].includes(k)))};hist('Shopee','Parâmetros de precificação atualizados');toast('Parâmetros Shopee salvos')}catch(e){toast(e.message)}}
function saveShopeeProduct(){const id=$('sh-product')?.value;if(!id)return toast('Selecione um produto da ficha técnica');try{const d=shopeeRead();state.shopee={...state.shopee,products:{...state.shopee?.products,[id]:d}};hist('Shopee','Simulação de produto salva');toast('Simulação Shopee salva')}catch(e){toast(e.message)}}
function shopeePrint(){shopeeUpdate();window.print()}
